// Generated by gencpp from file william_srv/AddTwoInts.msg
// DO NOT EDIT!


#ifndef WILLIAM_SRV_MESSAGE_ADDTWOINTS_H
#define WILLIAM_SRV_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <william_srv/AddTwoIntsRequest.h>
#include <william_srv/AddTwoIntsResponse.h>


namespace william_srv
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace william_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::william_srv::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::william_srv::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::william_srv::AddTwoInts > {
  static const char* value()
  {
    return "william_srv/AddTwoInts";
  }

  static const char* value(const ::william_srv::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::william_srv::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::william_srv::AddTwoInts > 
template<>
struct MD5Sum< ::william_srv::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::william_srv::AddTwoInts >::value();
  }
  static const char* value(const ::william_srv::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::william_srv::AddTwoIntsRequest> should match 
// service_traits::DataType< ::william_srv::AddTwoInts > 
template<>
struct DataType< ::william_srv::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::william_srv::AddTwoInts >::value();
  }
  static const char* value(const ::william_srv::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::william_srv::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::william_srv::AddTwoInts > 
template<>
struct MD5Sum< ::william_srv::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::william_srv::AddTwoInts >::value();
  }
  static const char* value(const ::william_srv::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::william_srv::AddTwoIntsResponse> should match 
// service_traits::DataType< ::william_srv::AddTwoInts > 
template<>
struct DataType< ::william_srv::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::william_srv::AddTwoInts >::value();
  }
  static const char* value(const ::william_srv::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WILLIAM_SRV_MESSAGE_ADDTWOINTS_H
